repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.300
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        additional_dependencies: ["lmdb", "fastapi", "uvicorn", "requests", "pydantic"]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest --cov
        language: system
        pass_filenames: false

