name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install
        run: |
          python -m pip install -U pip
          pip install .[server] pre-commit
      - name: Lint and Test
        run: |
          pre-commit run --all-files
          pytest -q

